### ISSUE TITLE
Errors install mysqlnd_ms with PHP 5.4 on Debian

### ISSUE THREAD

**Issue by ctrlbrk42** [sergiotabanelli/mysqlnd_ms#20]
Please help

# git clone https://github.com/sergiotabanelli/mysqlnd_ms.git
Cloning into 'mysqlnd_ms'...
remote: Enumerating objects: 87, done.
remote: Counting objects: 100% (87/87), done.
remote: Compressing objects: 100% (64/64), done.
remote: Total 1954 (delta 45), reused 52 (delta 20), pack-reused 1867
Receiving objects: 100% (1954/1954), 1.46 MiB | 0 bytes/s, done.
Resolving deltas: 100% (1299/1299), done.

08:45 PM [pegasus]~ root # cd mysqlnd_ms/

# phpize
Configuring for:
PHP Api Version:         20100412
Zend Module Api No:      20100525
Zend Extension Api No:   220100525

# ./configure
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for PHP prefix... /usr
checking for PHP includes... -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib
checking for PHP extension directory... /usr/lib/php5/20100525
checking for PHP installed headers prefix... /usr/include/php5
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... no
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
checking for gawk... gawk
checking whether to enable mysqlnd_ms support... yes, shared
checking whether to enable table filter in mysqlnd_ms... no
checking whether to query caching through mysqlnd_qc in mysqlnd_ms... no
checking libxml2 install dir... no
checking for libmemcached... no
checking for libmemcached location... /usr
checking for xml2-config path... /usr/bin/xml2-config
checking whether libxml build works... yes
checking how to print strings... printf
checking for a sed that does not truncate output... (cached) /bin/sed
checking for fgrep... /bin/grep -F
checking for ld used by cc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking for gawk... (cached) gawk
checking command to parse /usr/bin/nm -B output from cc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC -DPIC
checking if cc PIC flag -fPIC -DPIC works... yes
checking if cc static flag -static works... yes
checking if cc supports -c -o file.o... yes
checking if cc supports -c -o file.o... (cached) yes
checking whether the cc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
configure: creating ./config.status
config.status: creating config.h
config.status: executing libtool commands

# make
/bin/bash /root/mysqlnd_ms/libtool --mode=compile cc  -I. -I/root/mysqlnd_ms -DPHP_ATOM_INC -I/root/mysqlnd_ms/include -I/root/mysqlnd_ms/main -I/root/mysqlnd_ms -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -I/usr/include/libxml2  -DHAVE_CONFIG_H  -g -O2   -c /root/mysqlnd_ms/php_mysqlnd_ms.c -o php_mysqlnd_ms.lo
libtool: compile:  cc -I. -I/root/mysqlnd_ms -DPHP_ATOM_INC -I/root/mysqlnd_ms/include -I/root/mysqlnd_ms/main -I/root/mysqlnd_ms -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -I/usr/include/libxml2 -DHAVE_CONFIG_H -g -O2 -c /root/mysqlnd_ms/php_mysqlnd_ms.c  -fPIC -DPIC -o .libs/php_mysqlnd_ms.o
/bin/bash /root/mysqlnd_ms/libtool --mode=compile cc  -I. -I/root/mysqlnd_ms -DPHP_ATOM_INC -I/root/mysqlnd_ms/include -I/root/mysqlnd_ms/main -I/root/mysqlnd_ms -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -I/usr/include/libxml2  -DHAVE_CONFIG_H  -g -O2   -c /root/mysqlnd_ms/mysqlnd_ms.c -o mysqlnd_ms.lo
libtool: compile:  cc -I. -I/root/mysqlnd_ms -DPHP_ATOM_INC -I/root/mysqlnd_ms/include -I/root/mysqlnd_ms/main -I/root/mysqlnd_ms -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -I/usr/include/libxml2 -DHAVE_CONFIG_H -g -O2 -c /root/mysqlnd_ms/mysqlnd_ms.c  -fPIC -DPIC -o .libs/mysqlnd_ms.o
/root/mysqlnd_ms/mysqlnd_ms.c: In function ‘mysqlnd_ms_set_tx’:
/root/mysqlnd_ms/mysqlnd_ms.c:214:16: error: ‘struct st_mysqlnd_conn_data_methods’ has no member named ‘tx_begin’
   ret = conn->m->tx_begin(conn, mode, NULL TSRMLS_CC);
                ^~
/root/mysqlnd_ms/mysqlnd_ms.c: In function ‘mysqlnd_ms_clone_client_options’:
/root/mysqlnd_ms/mysqlnd_ms.c:2461:5: error: ‘MYSQLND_NET {aka struct st_mysqlnd_net}’ has no member named ‘data’
  vio->data->options.net_read_buffer_size = proxy_vio->data->options.net_read_buffer_size;
     ^~
/root/mysqlnd_ms/mysqlnd_ms.c:2461:53: error: ‘MYSQLND_NET {aka struct st_mysqlnd_net}’ has no member named ‘data’
  vio->data->options.net_read_buffer_size = proxy_vio->data->options.net_read_buffer_size;
                                                     ^~
/root/mysqlnd_ms/mysqlnd_ms.c:2462:5: error: ‘MYSQLND_NET {aka struct st_mysqlnd_net}’ has no member named ‘data’
  vio->data->options.timeout_connect = proxy_vio->data->options.timeout_connect;
     ^~
/root/mysqlnd_ms/mysqlnd_ms.c:2462:48: error: ‘MYSQLND_NET {aka struct st_mysqlnd_net}’ has no member named ‘data’
  vio->data->options.timeout_connect = proxy_vio->data->options.timeout_connect;
                                                ^~
/root/mysqlnd_ms/mysqlnd_ms.c:2463:5: error: ‘MYSQLND_NET {aka struct st_mysqlnd_net}’ has no member named ‘data’
  vio->data->options.timeout_read = proxy_vio->data->options.timeout_read;
     ^~
/root/mysqlnd_ms/mysqlnd_ms.c:2463:45: error: ‘MYSQLND_NET {aka struct st_mysqlnd_net}’ has no member named ‘data’
  vio->data->options.timeout_read = proxy_vio->data->options.timeout_read;
                                             ^~
/root/mysqlnd_ms/mysqlnd_ms.c:2464:5: error: ‘MYSQLND_NET {aka struct st_mysqlnd_net}’ has no member named ‘data’
  vio->data->options.timeout_write = proxy_vio->data->options.timeout_write;
     ^~
/root/mysqlnd_ms/mysqlnd_ms.c:2464:46: error: ‘MYSQLND_NET {aka struct st_mysqlnd_net}’ has no member named ‘data’
  vio->data->options.timeout_write = proxy_vio->data->options.timeout_write;
                                              ^~
/root/mysqlnd_ms/mysqlnd_ms.c:2465:5: error: ‘MYSQLND_NET {aka struct st_mysqlnd_net}’ has no member named ‘data’
  vio->data->options.ssl_verify_peer = proxy_vio->data->options.ssl_verify_peer;
     ^~
/root/mysqlnd_ms/mysqlnd_ms.c:2465:48: error: ‘MYSQLND_NET {aka struct st_mysqlnd_net}’ has no member named ‘data’
  vio->data->options.ssl_verify_peer = proxy_vio->data->options.ssl_verify_peer;
                                                ^~
/root/mysqlnd_ms/mysqlnd_ms.c:2466:15: error: ‘MYSQLND_NET {aka struct st_mysqlnd_net}’ has no member named ‘data’
  if (proxy_vio->data->options.ssl_ca && PASS != MS_CALL_ORIGINAL_CONN_DATA_METHOD(set_client_option)(conn,
               ^~
/root/mysqlnd_ms/mysqlnd_ms.c:2467:32: error: ‘MYSQLND_NET {aka struct st_mysqlnd_net}’ has no member named ‘data’
   MYSQLND_OPT_SSL_CA, proxy_vio->data->options.ssl_ca TSRMLS_CC)) {
                                ^~
/root/mysqlnd_ms/mysqlnd_ms.c:2470:15: error: ‘MYSQLND_NET {aka struct st_mysqlnd_net}’ has no member named ‘data’
  if (proxy_vio->data->options.ssl_capath && PASS != MS_CALL_ORIGINAL_CONN_DATA_METHOD(set_client_option)(conn,
               ^~
/root/mysqlnd_ms/mysqlnd_ms.c:2471:36: error: ‘MYSQLND_NET {aka struct st_mysqlnd_net}’ has no member named ‘data’
   MYSQLND_OPT_SSL_CAPATH, proxy_vio->data->options.ssl_capath TSRMLS_CC)) {
                                    ^~
/root/mysqlnd_ms/mysqlnd_ms.c:2474:15: error: ‘MYSQLND_NET {aka struct st_mysqlnd_net}’ has no member named ‘data’
  if (proxy_vio->data->options.ssl_cert && PASS != MS_CALL_ORIGINAL_CONN_DATA_METHOD(set_client_option)(conn,
               ^~
/root/mysqlnd_ms/mysqlnd_ms.c:2475:34: error: ‘MYSQLND_NET {aka struct st_mysqlnd_net}’ has no member named ‘data’
   MYSQLND_OPT_SSL_CERT, proxy_vio->data->options.ssl_cert TSRMLS_CC)) {
                                  ^~
/root/mysqlnd_ms/mysqlnd_ms.c:2478:15: error: ‘MYSQLND_NET {aka struct st_mysqlnd_net}’ has no member named ‘data’
  if (proxy_vio->data->options.ssl_cipher && PASS != MS_CALL_ORIGINAL_CONN_DATA_METHOD(set_client_option)(conn,
               ^~
/root/mysqlnd_ms/mysqlnd_ms.c:2479:36: error: ‘MYSQLND_NET {aka struct st_mysqlnd_net}’ has no member named ‘data’
   MYSQLND_OPT_SSL_CIPHER, proxy_vio->data->options.ssl_cipher TSRMLS_CC)) {
                                    ^~
/root/mysqlnd_ms/mysqlnd_ms.c:2482:15: error: ‘MYSQLND_NET {aka struct st_mysqlnd_net}’ has no member named ‘data’
  if (proxy_vio->data->options.ssl_key && PASS != MS_CALL_ORIGINAL_CONN_DATA_METHOD(set_client_option)(conn,
               ^~
/root/mysqlnd_ms/mysqlnd_ms.c:2483:33: error: ‘MYSQLND_NET {aka struct st_mysqlnd_net}’ has no member named ‘data’
   MYSQLND_OPT_SSL_KEY, proxy_vio->data->options.ssl_key TSRMLS_CC)) {
                                 ^~
/root/mysqlnd_ms/mysqlnd_ms.c:2486:15: error: ‘MYSQLND_NET {aka struct st_mysqlnd_net}’ has no member named ‘data’
  if (proxy_vio->data->options.ssl_passphrase && PASS != MS_CALL_ORIGINAL_CONN_DATA_METHOD(set_client_option)(conn,
               ^~
/root/mysqlnd_ms/mysqlnd_ms.c:2487:40: error: ‘MYSQLND_NET {aka struct st_mysqlnd_net}’ has no member named ‘data’
   MYSQLND_OPT_SSL_PASSPHRASE, proxy_vio->data->options.ssl_passphrase TSRMLS_CC)) {
                                        ^~
/root/mysqlnd_ms/mysqlnd_ms.c:126:50: error: ‘MYSQLND_NET {aka struct st_mysqlnd_net}’ has no member named ‘data’
 #define _MS_PROTOCOL_CONN_DATA_NET_SPK(cnet) cnet->data->options.sha256_server_public_key
                                                  ^
/root/mysqlnd_ms/mysqlnd_ms.c:2490:6: note: in expansion of macro ‘_MS_PROTOCOL_CONN_DATA_NET_SPK’
  if (_MS_PROTOCOL_CONN_DATA_NET_SPK(proxy_net) && PASS != MS_CALL_ORIGINAL_CONN_DATA_METHOD(set_client_option)(conn,
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/mysqlnd_ms/mysqlnd_ms.c:126:50: error: ‘MYSQLND_NET {aka struct st_mysqlnd_net}’ has no member named ‘data’
 #define _MS_PROTOCOL_CONN_DATA_NET_SPK(cnet) cnet->data->options.sha256_server_public_key
                                                  ^
/root/mysqlnd_ms/mysqlnd_ms.c:2491:28: note: in expansion of macro ‘_MS_PROTOCOL_CONN_DATA_NET_SPK’
   MYSQL_SERVER_PUBLIC_KEY, _MS_PROTOCOL_CONN_DATA_NET_SPK(proxy_net) TSRMLS_CC)) {
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/mysqlnd_ms/mysqlnd_ms.c: In function ‘mysqlnd_ms_read_header’:
/root/mysqlnd_ms/mysqlnd_ms.c:5775:34: error: ‘MYSQLND_NET {aka struct st_mysqlnd_net}’ has no member named ‘data’
  DBG_INF_FMT("compressed=%u", net->data->compressed);
                                  ^~
/root/mysqlnd_ms/mysqlnd_ms.c:122:28: error: ‘MYSQLND_NET {aka struct st_mysqlnd_net}’ has no member named ‘data’
 #define _ms_net_receive net->data->m.receive_ex
                            ^
/root/mysqlnd_ms/mysqlnd_ms.c:5776:14: note: in expansion of macro ‘_ms_net_receive’
  if (FAIL == _ms_net_receive(_MS_PROTOCOL_CONN_READ_NET_A, buffer, MYSQLND_HEADER_SIZE, conn_stats, error_info TSRMLS_CC)) {
              ^~~~~~~~~~~~~~~
/root/mysqlnd_ms/mysqlnd_ms.c:5790:9: error: ‘MYSQLND_NET {aka struct st_mysqlnd_net}’ has no member named ‘data’
  if (net->data->compressed || _ms_net_packet_no == header->packet_no) {
         ^~
/root/mysqlnd_ms/mysqlnd_ms.c: In function ‘mysqlnd_ms_read_packet_header_and_body’:
/root/mysqlnd_ms/mysqlnd_ms.c:122:28: error: ‘MYSQLND_NET {aka struct st_mysqlnd_net}’ has no member named ‘data’
 #define _ms_net_receive net->data->m.receive_ex
                            ^
/root/mysqlnd_ms/mysqlnd_ms.c:5830:14: note: in expansion of macro ‘_ms_net_receive’
  if (FAIL == _ms_net_receive(_MS_PROTOCOL_CONN_READ_NET_A, (buf), header->size, (conn)->stats, ((conn)->error_info) TSRMLS_CC)) {
              ^~~~~~~~~~~~~~~
/root/mysqlnd_ms/mysqlnd_ms.c: In function ‘mysqlnd_ms_register_hooks’:
/root/mysqlnd_ms/mysqlnd_ms.c:6320:30: error: ‘struct st_mysqlnd_conn_data_methods’ has no member named ‘tx_commit_or_rollback’; did you mean ‘tx_rollback’?
  ms_orig_mysqlnd_conn_methods->tx_commit_or_rollback  = MYSQLND_METHOD(mysqlnd_ms, tx_commit_or_rollback);
                              ^~
In file included from /root/mysqlnd_ms/mysqlnd_ms_xa.h:29:0,
                 from /root/mysqlnd_ms/mysqlnd_ms.c:27:
/usr/include/php5/ext/mysqlnd/mysqlnd.h:259:39: error: ‘php_mysqlnd_ms_tx_commit_or_rollback_pub’ undeclared (first use in this function)
 #define MYSQLND_METHOD(class, method) php_##class##_##method##_pub
                                       ^
/root/mysqlnd_ms/mysqlnd_ms.c:6320:57: note: in expansion of macro ‘MYSQLND_METHOD’
  ms_orig_mysqlnd_conn_methods->tx_commit_or_rollback  = MYSQLND_METHOD(mysqlnd_ms, tx_commit_or_rollback);
                                                         ^~~~~~~~~~~~~~
/usr/include/php5/ext/mysqlnd/mysqlnd.h:259:39: note: each undeclared identifier is reported only once for each function it appears in
 #define MYSQLND_METHOD(class, method) php_##class##_##method##_pub
                                       ^
/root/mysqlnd_ms/mysqlnd_ms.c:6320:57: note: in expansion of macro ‘MYSQLND_METHOD’
  ms_orig_mysqlnd_conn_methods->tx_commit_or_rollback  = MYSQLND_METHOD(mysqlnd_ms, tx_commit_or_rollback);
                                                         ^~~~~~~~~~~~~~
/root/mysqlnd_ms/mysqlnd_ms.c:6321:30: error: ‘struct st_mysqlnd_conn_data_methods’ has no member named ‘tx_begin’
  ms_orig_mysqlnd_conn_methods->tx_begin     = MYSQLND_METHOD(mysqlnd_ms, tx_begin);
                              ^~
In file included from /root/mysqlnd_ms/mysqlnd_ms_xa.h:29:0,
                 from /root/mysqlnd_ms/mysqlnd_ms.c:27:
/usr/include/php5/ext/mysqlnd/mysqlnd.h:259:39: error: ‘php_mysqlnd_ms_tx_begin_pub’ undeclared (first use in this function)
 #define MYSQLND_METHOD(class, method) php_##class##_##method##_pub
                                       ^
/root/mysqlnd_ms/mysqlnd_ms.c:6321:47: note: in expansion of macro ‘MYSQLND_METHOD’
  ms_orig_mysqlnd_conn_methods->tx_begin     = MYSQLND_METHOD(mysqlnd_ms, tx_begin);
                                               ^~~~~~~~~~~~~~
Makefile:198: recipe for target 'mysqlnd_ms.lo' failed
make: *** [mysqlnd_ms.lo] Error 1

**Comment by sergiotabanelli** [comment]
Did you install php development package, libmemcached development package and libxml development package?  Anyway I will check it next weekend.

**Comment by sergiotabanelli** [comment]
@ctrlbrk42 Are You trying to compile with 5.6 ZTS?? If Yes, ZTS is not supported, and with php 5.6 I am pretty sure it want compile... for ZTS support check #8 !!

**Comment by ctrlbrk42** [comment]
> @ctrlbrk42 Are You trying to compile with 5.6 ZTS?? If Yes, ZTS is not supported, and with php 5.6 I am pretty sure it want compile... for ZTS support check #8 !!

Yes, I have a fairly unique config.

# php -v
PHP 5.4.45-0+deb7u14 (cli) (built: May  9 2018 16:47:00)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.2, Copyright (c) 1999-2013, by Zend Technologies

**Comment by ctrlbrk42** [comment]
Sorry just realized this box is PHP 5.4 not 5.6, so my subject line is wrong.  But rest is accurate.

**Comment by sergiotabanelli** [comment]
Sorry, but I don't have that environment, my tests starts from 5.5, anyway for 5.4 you can use the original pecl version of the mysqlnd_ms plugin https://pecl.php.net/package/mysqlnd_ms
